### ISSUE TITLE
Create User - JavaScript has hard-coded values that should be coming from DNN

### ISSUE THREAD

**Issue by jeremy-farrance** [UpendoVentures/Upendo-Dnn-UserManager#83]
## Software Versions  
- DNN:  09.12.00  
- Module:  01.01.01  

## To Reproduce  
You can view the hard-coded values minLength and minNumberOfSpecialChars [here in Create.cshtml](https://github.com/UpendoVentures/Upendo-Dnn-UserManager/blob/eca38fee6c9c64c254af06238259ec3f15bc52d3/Modules/UserManager/Views/UserManage/Create.cshtml#L115)

## Expected behavior  
These values should be coming from DNN (set in web.config)

**Comment by WillStrohl** [comment]
@alejoroman0605 FYI...
