### ISSUE TITLE
SI: Remove GlyphIcons (Bootstrap 3) and Replace With...

### ISSUE THREAD

**Issue by jeremy-farrance** [UpendoVentures/Upendo-Dnn-UserManager#85]
## Is your feature request related to a problem?
The Icons in use are coming from Bootstrap 3 GlyphIcons. They are pretty old, they look outdated, and it will help take a step towards the likely near-future removal of Bootstrap 3 altogether.

## Describe the solution you'd like
Replace them with a standalone open source icon set. The two most likely candidates are:

- [Bootstrap Icons](https://icons.getbootstrap.com/) - standalone project with no ties/dependencies to Bootstrap (4, 5, etc)
- [Google Icons](https://fonts.google.com/icons?icon.set=Material+Icons) - standalone (with more modern Symbols option)

## Describe alternatives you've considered
There are other free options like FontAwesome and HeroIcons (and many others). But the two above seem to align most with this project's long term needs (IMHO - JRF).

## Additional context
I can probably contribute a PR with a complete solution for this change. However, I wanted to get feedback. 

- Is this a good step forward or just an unnecessary change?
- Some voting or guidance on the icon set to switch to; Google vs. Bootstrap? Or should another alternative be considered?

### A visual?
Here is what the Google Icons would look like. The Actions column shows replacements of the 3 existing Glyphicons. The Icons under Status are showing when the user is super, is unauthorized, and is deleted. The Icon to the right of Username header is showing the current sort direction (though not working).

![image](https://github.com/UpendoVentures/Upendo-Dnn-UserManager/assets/653301/b9152cf0-1f53-4eb0-b6c2-847b9e25d06a)

**Comment by WillStrohl** [comment]
I love this update.  Yes, please feel free to do a PR if you'd like.  Thanks, @jeremy-farrance!  💪🏽

**Comment by WillStrohl** [comment]
Closed by PR #94 (sponsored by a client).
